apiVersion: apps/v1
kind: Deployment
metadata:
  name: dc1
  labels:
    app.kubernetes.io/part-of: factory
    app: dc1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dc1
  template:
    metadata:
      labels:
        app: dc1
    spec:
      containers:
      - name: dc1
        image: fabgen5/server
        ports:
        - containerPort: 8080